//200 family
const OK = 200;
const CREATED = 201;
const ACCEPTED = 202;

//400 family
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const NOT_ACCEPTABLE = 406;

//500 family
const INTERNAL_SERVER = 500;
const SERVER_BUSY = 503;

export default {
  OK,
  CREATED,
  ACCEPTED,
  BAD_REQUEST,
  UNAUTHORIZED,
  NOT_FOUND,
  INTERNAL_SERVER,
  NOT_ACCEPTABLE,
  SERVER_BUSY,
};
