export enum SocketAdminEvents {
  ADD_CITY = "ADD_CITY",
  EDIT_CITY = "EDIT_CITY",
  ADD_REPORT_REASON = "ADD_REPORT_REASON",
  EDIT_REPORT_REASON = "EDIT_REPORT_REASON",
}

export enum SocketClientEvents {
  NEW_NOTIFICATION = "NEW_NOTIFICATION",
  SEND_MESSAGE = "SEND_MESSAGE",
  NEW_RESERVATION_REQUEST = "NEW_RESERVATION_REQUEST",
}
